fix(ci): adapt coverage check

diff --git a/.gitea/workflows/golang-tests.yaml b/.gitea/workflows/golang-tests.yaml
--- a/.gitea/workflows/golang-tests.yaml
+++ b/.gitea/workflows/golang-tests.yaml
@@ -48,6 +48,7 @@ jobs:
         echo "Total coverage: ${coverage}%"
     - name: Fail if coverage is to low
       run: |
-        if (( $(echo "${total_coverage} < 50" | bc -l) )); then
-          echo "ERROR: Coverage (${total_coverage}%) is below the threshold (50%)."
+        if (( ${total_coverage%.*} < 50 )); then
+          echo "ERROR: Coverage (${total_coverage}%) is below the threshold (50%)." 1>&2
+          exit 1
         fi
