fix(ci): define threshold as var

diff --git a/.gitea/workflows/golang-tests.yaml b/.gitea/workflows/golang-tests.yaml
--- a/.gitea/workflows/golang-tests.yaml
+++ b/.gitea/workflows/golang-tests.yaml
@@ -48,9 +48,10 @@ jobs:
         echo "Total coverage: ${coverage}%"
     - name: Fail if coverage is to low
       run: |
+        threshold=50
         total_coverage=${{ steps.coverage.outputs.total_coverage }}
 
-        if (( ${total_coverage%.*} < 50 )); then
-          echo "ERROR: Coverage (${total_coverage}%) is below the threshold (50%)." 1>&2
+        if (( ${total_coverage%.*} < ${threshold} )); then
+          echo "ERROR: Coverage (${total_coverage}%) is below the threshold (${threshold}%)." 1>&2
           exit 1
         fi
